//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volume_Final
    {
        public System.Guid Id { get; set; }
        public int UploadedFileDetailsId { get; set; }
        public string Outlet { get; set; }
        public string Category_Code { get; set; }
        public string Product_Key { get; set; }
        public string geogkey { get; set; }
        public string week { get; set; }
        public string SalesComponent { get; set; }
        public Nullable<double> Dueto_value { get; set; }
        public string PrimaryCausalKey { get; set; }
        public Nullable<double> causal_value { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual UploadedFileDetail UploadedFileDetail { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
