//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Transactions
    {
        public int Id { get; set; }
        public string VoucherNumber { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public double DebitAmount { get; set; }
        public double CreditAmount { get; set; }
        public double RunningBalance { get; set; }
    
        public virtual Voucher Voucher { get; set; }
    }
}
