//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int code { get; set; }
        public string ac_name { get; set; }
        public int parent { get; set; }
        public string type { get; set; }
        public int levelno { get; set; }
        public string @fixed { get; set; }
        public string direct { get; set; }
        public Nullable<decimal> open_bal { get; set; }
        public Nullable<System.DateTime> dt { get; set; }
        public Nullable<int> active { get; set; }
        public int cntr { get; set; }
    }
}
