//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        public string AssetID { get; set; }
        public string EnterpriseID { get; set; }
        public string DepartmentID { get; set; }
        public string AssetType { get; set; }
        public string AssetDescription { get; set; }
        public Nullable<System.DateTime> AcquireDate { get; set; }
        public Nullable<System.DateTime> WarrentyExpiryDate { get; set; }
        public string VD_FirstName { get; set; }
        public string VD_MiddleName { get; set; }
        public string VD_LastName { get; set; }
        public string VD_Designation { get; set; }
        public string VD_Email { get; set; }
        public string VD_Phone { get; set; }
        public string VD_Fax { get; set; }
        public string VD_MobileNo { get; set; }
        public string Create_UserID { get; set; }
        public string Create_UserName { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<System.DateTime> Sys_Time { get; set; }
        public Nullable<System.DateTime> Sys_Date { get; set; }
        public string EmployerId { get; set; }
        public string MethodOfDepreciation { get; set; }
        public string BranchId { get; set; }
        public int NoOfYearsDepreciationCompleted { get; set; }
        public double CostOfAsset { get; set; }
        public double SlavageValue { get; set; }
        public int NoOfYearsOfLife { get; set; }
        public string PurchaseType { get; set; }
        public int RelatedFixedAssetsAccountId { get; set; }
        public int RelatedAccumulatedDepreciation { get; set; }
        public int RelatedDepreciationExpense { get; set; }
        public bool IsPosted { get; set; }
        public bool IsApproved { get; set; }
        public bool IsRejected { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Asset Assets1 { get; set; }
        public virtual Asset Asset1 { get; set; }
    }
}
