//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Branch_Master
    {
        public string BranchCode { get; set; }
        public string RoutingNumber { get; set; }
        public string IntermediaryRoutingNumber { get; set; }
        public string BankName { get; set; }
        public string BankNameLocal { get; set; }
        public string BankAcronymName { get; set; }
        public Nullable<int> DigitsInAccountNumber { get; set; }
        public string IBANBankCode { get; set; }
        public string BankAgentID { get; set; }
        public string ValidateBankAccountNumber { get; set; }
        public string ValidateCharactersInBankAccount { get; set; }
        public string ActivateEpay { get; set; }
        public string MainBranchID { get; set; }
        public string MainBranchName { get; set; }
        public string MainBAddress { get; set; }
        public string MainBCountry { get; set; }
        public string MainBState { get; set; }
        public string MainBCity { get; set; }
        public string MainBBuilding { get; set; }
        public string MainBFloorNo { get; set; }
        public string MainBStreet { get; set; }
        public string MainBPhone { get; set; }
        public string MainBFax { get; set; }
        public string MainBWebsite { get; set; }
        public string ContactOfficerName { get; set; }
        public string ContactOfficerPhone { get; set; }
        public string ContactOfficerFax { get; set; }
        public string ContactOfficerMobile { get; set; }
        public string ContactOfficerEmail { get; set; }
        public string BankCode { get; set; }
    
        public virtual Bank_Master Bank_Master { get; set; }
    }
}
