//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Order_Note
    {
        public string Delivery_Order_No { get; set; }
        public string Order_ID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string ContactPersonName { get; set; }
        public string CPMobileNo { get; set; }
        public Nullable<System.DateTime> DateOfDelivery { get; set; }
        public string ReorderLevelQuantity { get; set; }
        public string Create_UserID { get; set; }
        public string Create_UserName { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<System.DateTime> Sys_Time { get; set; }
        public Nullable<System.DateTime> Sys_Date { get; set; }
        public string EmployerID { get; set; }
        public string Customer_ID { get; set; }
        public string Customer_BillNo { get; set; }
        public string Remarks { get; set; }
    
        public virtual Sales_Order Sales_Order { get; set; }
    }
}
