//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.Assets = new HashSet<Asset>();
        }
    
        public string DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public Nullable<bool> CostCenter { get; set; }
        public string EmployerID { get; set; }
        public string ReportingDepartmentID { get; set; }
        public string MD_FirstName { get; set; }
        public string MD_MiddleName { get; set; }
        public string MD_LastName { get; set; }
        public string MD_Email { get; set; }
        public string MD_Designation { get; set; }
        public string MD_Phone { get; set; }
        public string MD_Fax { get; set; }
        public string MD_MobileNo { get; set; }
        public string MD_PreferredContactPerson { get; set; }
        public string Create_UserID { get; set; }
        public string Create_UserName { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<System.DateTime> Sys_Time { get; set; }
        public Nullable<System.DateTime> Sys_Date { get; set; }
        public string Dep_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asset> Assets { get; set; }
    }
}
