//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_CityMaster
    {
        public int city_id { get; set; }
        public string city_name { get; set; }
        public string city_code { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<bool> city_status { get; set; }
        public Nullable<int> district_id { get; set; }
    }
}
