//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_Countries
    {
        public int country_id { get; set; }
        public string country_name { get; set; }
        public string country_code { get; set; }
        public Nullable<bool> country_status { get; set; }
        public string Currency { get; set; }
        public string currency_code { get; set; }
        public string currency_symbol { get; set; }
    }
}
