//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_EsmartServices
    {
        public long Eservice_id { get; set; }
        public string Eservice_name { get; set; }
        public string Eservice_type { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Sys_date { get; set; }
        public Nullable<bool> Eservice_status { get; set; }
    }
}
