//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagePermission
    {
        public int Id { get; set; }
        public string Module { get; set; }
        public string Document { get; set; }
        public string Role_Id { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
    }
}
