//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Projects()
        {
            this.tbl_Stock_Items_Transactions = new HashSet<tbl_Stock_Items_Transactions>();
        }
    
        public long project_id { get; set; }
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<bool> CostCenter { get; set; }
        public string LocalName { get; set; }
        public string Risk_Description { get; set; }
        public Nullable<long> o_id { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public string Location { get; set; }
        public string Project_Manager { get; set; }
        public Nullable<System.DateTime> Plan_startdt { get; set; }
        public Nullable<System.DateTime> Actual_startdt { get; set; }
        public Nullable<System.DateTime> Plan_Enddt { get; set; }
        public Nullable<System.DateTime> Actual_Enddt { get; set; }
        public string Client { get; set; }
        public string Contact_no { get; set; }
        public string Contact_Description { get; set; }
        public Nullable<System.DateTime> Contact_StartDt { get; set; }
        public Nullable<System.DateTime> Contact_EndDt { get; set; }
        public string Project_RefNo { get; set; }
        public string NoofShift_Req { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<System.TimeSpan> Sys_Time { get; set; }
        public Nullable<System.DateTime> Sys_Date { get; set; }
        public string NoofPositions_Req { get; set; }
        public string NoofEmp_Assigned { get; set; }
        public string Vaccant_positions { get; set; }
        public Nullable<bool> Del_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stock_Items_Transactions> tbl_Stock_Items_Transactions { get; set; }
    }
}
