//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PQuotationTransaction
    {
        public long PQTrans_Id { get; set; }
        public Nullable<long> stockitem_id { get; set; }
        public string Description { get; set; }
        public Nullable<long> Qty { get; set; }
        public Nullable<long> unit_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public string Discount_type { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public Nullable<long> PQuotation_Id { get; set; }
        public Nullable<bool> del_status { get; set; }
    }
}
