//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Account_Transactions
    {
        public long AccTrans_Id { get; set; }
        public Nullable<long> Account_id { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public double DebitAmount { get; set; }
        public double CreditAmount { get; set; }
        public double RunningBalance { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public string narration { get; set; }
        public Nullable<long> As_id { get; set; }
        public string Balance_type { get; set; }
        public string currency { get; set; }
    
        public virtual tbl_Account_Transactions tbl_Account_Transactions1 { get; set; }
        public virtual tbl_Account_Transactions tbl_Account_Transactions2 { get; set; }
    }
}
