//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Logins
    {
        public long User_Id { get; set; }
        public string User_name { get; set; }
        public string Password { get; set; }
        public string CnfPassword { get; set; }
        public string Email { get; set; }
        public string Mobile_NO { get; set; }
        public Nullable<long> UserGrp_id { get; set; }
        public Nullable<long> Hint_id { get; set; }
        public Nullable<long> employee_id { get; set; }
        public Nullable<System.DateTime> sysdate { get; set; }
        public Nullable<System.TimeSpan> systime { get; set; }
        public string Hint_Name { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
