//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ErrorTrack
    {
        public long ErrTrackId { get; set; }
        public string DBName { get; set; }
        public Nullable<long> ErrNumber { get; set; }
        public Nullable<long> ErrSeverity { get; set; }
        public Nullable<long> ErrState { get; set; }
        public string ErrProcedure { get; set; }
        public Nullable<long> ErrLine { get; set; }
        public string ErrMessage { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
