//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseQuotation
    {
        public long PQuotation_Id { get; set; }
        public string QuotationID { get; set; }
        public Nullable<long> emp_id { get; set; }
        public Nullable<long> b_id { get; set; }
        public Nullable<long> o_id { get; set; }
        public Nullable<long> project_id { get; set; }
        public Nullable<long> purchase_id { get; set; }
        public Nullable<long> supp_id { get; set; }
        public string Remarks { get; set; }
        public string updateuser_id { get; set; }
        public string updateuser_name { get; set; }
        public Nullable<System.TimeSpan> sys_time { get; set; }
        public Nullable<System.DateTime> sys_date { get; set; }
        public Nullable<bool> del_status { get; set; }
    }
}
