//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseReq_Transactions
    {
        public long purchase_TransId { get; set; }
        public Nullable<long> sl_no { get; set; }
        public Nullable<long> stockitem_id { get; set; }
        public string Description { get; set; }
        public Nullable<long> Qty { get; set; }
        public Nullable<long> unit_id { get; set; }
        public Nullable<System.DateTime> sysdate { get; set; }
        public Nullable<System.TimeSpan> sys_time { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<long> Req_TransId { get; set; }
        public Nullable<long> purchase_id { get; set; }
        public Nullable<bool> del_status { get; set; }
    }
}
