//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AccountsSegments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_AccountsSegments()
        {
            this.tbl_MaterialRequest = new HashSet<tbl_MaterialRequest>();
        }
    
        public long As_id { get; set; }
        public Nullable<long> emp_id { get; set; }
        public Nullable<long> b_id { get; set; }
        public Nullable<long> o_id { get; set; }
        public Nullable<long> project_id { get; set; }
        public Nullable<System.DateTime> trans_date { get; set; }
        public string Narration { get; set; }
        public string VoucherNumber { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public string Type { get; set; }
        public Nullable<long> asset_id { get; set; }
        public Nullable<System.DateTime> Transaction_date { get; set; }
        public Nullable<System.TimeSpan> sys_time { get; set; }
        public Nullable<System.DateTime> sys_date { get; set; }
        public Nullable<long> VoucherNo { get; set; }
        public Nullable<int> approved_status { get; set; }
        public string remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MaterialRequest> tbl_MaterialRequest { get; set; }
    }
}
