//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Employers()
        {
            this.tbl_Assets = new HashSet<tbl_Assets>();
            this.tbl_ChartOfAccount = new HashSet<tbl_ChartOfAccount>();
            this.tbl_Employees = new HashSet<tbl_Employees>();
            this.tbl_OrganizationUnits = new HashSet<tbl_OrganizationUnits>();
            this.tbl_Stock_Items_Transactions = new HashSet<tbl_Stock_Items_Transactions>();
        }
    
        public long emp_id { get; set; }
        public string EmployerID { get; set; }
        public string EmployerName { get; set; }
        public string ParentCompany { get; set; }
        public string PermanentRegistration { get; set; }
        public string LoginID { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateOfInception { get; set; }
        public Nullable<System.DateTime> DateOfExpiry { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string PostBox { get; set; }
        public string ZipCode { get; set; }
        public string LandLine { get; set; }
        public string Fax { get; set; }
        public string EmailAddress { get; set; }
        public string Website { get; set; }
        public string AR_FirstName { get; set; }
        public string AR_MiddleName { get; set; }
        public string AR_LastName { get; set; }
        public string AR_Email { get; set; }
        public string AR_Designation { get; set; }
        public string AR_Phone { get; set; }
        public string AR_Fax { get; set; }
        public string AR_MobileNo { get; set; }
        public string AR_PreferredContactPerson { get; set; }
        public string OCP_FirstName { get; set; }
        public string OCP_MiddleName { get; set; }
        public string OCP_LastName { get; set; }
        public string OCP_Email { get; set; }
        public string OCP_Designation { get; set; }
        public string OCP_Phone { get; set; }
        public string OCP_Fax { get; set; }
        public string OCP_MobileNo { get; set; }
        public string OCP_PreferredContactPerson { get; set; }
        public string Create_UserID { get; set; }
        public string Create_UserName { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<System.DateTime> Sys_Time { get; set; }
        public Nullable<System.DateTime> Sys_Date { get; set; }
        public string Empr_Status { get; set; }
        public string Employer_Banner { get; set; }
        public string Employer_Logo { get; set; }
        public string PrimaryFunctionalCurrency { get; set; }
        public string PayPeriodType { get; set; }
        public string EmployerTaxNo { get; set; }
        public string EmployerPanNo { get; set; }
        public string EmployerDinNo { get; set; }
        public string EmployerBinNo { get; set; }
        public Nullable<System.DateTime> FinancialYearStartDate { get; set; }
        public Nullable<System.DateTime> FinancialYearEndDate { get; set; }
        public Nullable<long> Ep_id { get; set; }
        public string ParentName { get; set; }
        public Nullable<long> country_id { get; set; }
        public Nullable<long> state_id { get; set; }
        public Nullable<long> city_id { get; set; }
        public Nullable<bool> del_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Assets> tbl_Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChartOfAccount> tbl_ChartOfAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Employees> tbl_Employees { get; set; }
        public virtual tbl_Employers tbl_Employers1 { get; set; }
        public virtual tbl_Employers tbl_Employers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrganizationUnits> tbl_OrganizationUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Stock_Items_Transactions> tbl_Stock_Items_Transactions { get; set; }
    }
}
