//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MaterialRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MaterialRequest()
        {
            this.tbl_MaterialRequest_Transactions = new HashSet<tbl_MaterialRequest_Transactions>();
        }
    
        public long MaterialReq_id { get; set; }
        public string materialrequestID { get; set; }
        public string contactperson_Name { get; set; }
        public string contactperson_MobileNo { get; set; }
        public string contactperson_Designation { get; set; }
        public Nullable<System.DateTime> projectstart_dt { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> dateof_delivery { get; set; }
        public string delivery_location { get; set; }
        public Nullable<long> As_id { get; set; }
        public Nullable<bool> del_status { get; set; }
    
        public virtual tbl_AccountsSegments tbl_AccountsSegments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MaterialRequest_Transactions> tbl_MaterialRequest_Transactions { get; set; }
    }
}
