//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseReqisition
    {
        public long purchase_id { get; set; }
        public string purchasereqID { get; set; }
        public Nullable<long> MaterialReq_id { get; set; }
        public Nullable<long> supp_id { get; set; }
        public string Supplier_ID { get; set; }
        public Nullable<long> emp_id { get; set; }
        public string EmployerID { get; set; }
        public Nullable<long> b_id { get; set; }
        public string BranchId { get; set; }
        public Nullable<long> o_id { get; set; }
        public string Org_ID { get; set; }
        public Nullable<long> project_id { get; set; }
        public string ProjectID { get; set; }
        public Nullable<System.DateTime> dateof_delivery { get; set; }
        public string delivery_location { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<System.TimeSpan> Sys_Time { get; set; }
        public Nullable<System.DateTime> Sys_Date { get; set; }
        public Nullable<bool> del_status { get; set; }
    }
}
