//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employees
    {
        public long employee_id { get; set; }
        public string EmployeeID { get; set; }
        public string ED_FirstName { get; set; }
        public string ED_MiddleName { get; set; }
        public string ED_LastName { get; set; }
        public string ED_Designation { get; set; }
        public string ED_Email { get; set; }
        public string DrivingLicenseNumber { get; set; }
        public Nullable<System.DateTime> DrivingLicenseIssueDate { get; set; }
        public Nullable<System.DateTime> DrivingLicenseExpiryDate { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string Ext { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        public Nullable<System.DateTime> WorkStartDate { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public string NoOfDependents { get; set; }
        public Nullable<int> ED_PreferredContactMode { get; set; }
        public string PassportNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string IssuingAuthority { get; set; }
        public string IssuingCountry { get; set; }
        public string VisaNo { get; set; }
        public Nullable<System.DateTime> Visa_IssueDate { get; set; }
        public Nullable<System.DateTime> Visa_ExpiryDate { get; set; }
        public string Visa_IssuingAuthority { get; set; }
        public string Visa_IssuingCountry { get; set; }
        public string WorkPermitNo { get; set; }
        public Nullable<System.DateTime> Work_IssueDate { get; set; }
        public Nullable<System.DateTime> Work_ExpiryDate { get; set; }
        public string Work_IssuingAuthority { get; set; }
        public string Work_IssuingCountry { get; set; }
        public string ECP_FirstName { get; set; }
        public string ECP_MiddleName { get; set; }
        public string ECP_LastName { get; set; }
        public string ECP_Email { get; set; }
        public string ECP_Relation { get; set; }
        public string ECP_Phone { get; set; }
        public string ECP_Fax { get; set; }
        public string ECP_MobileNo { get; set; }
        public string ECP_CountryOfResidency { get; set; }
        public Nullable<int> ECP_PreferredContactMode { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<System.DateTime> Sys_Time { get; set; }
        public Nullable<System.DateTime> Sys_Date { get; set; }
        public string Employee_Status { get; set; }
        public Nullable<long> emp_id { get; set; }
        public Nullable<long> b_id { get; set; }
        public Nullable<long> o_id { get; set; }
        public Nullable<long> project_id { get; set; }
        public Nullable<bool> del_status { get; set; }
    
        public virtual tbl_branches tbl_branches { get; set; }
        public virtual tbl_Employees tbl_Employees1 { get; set; }
        public virtual tbl_Employees tbl_Employees2 { get; set; }
        public virtual tbl_Employers tbl_Employers { get; set; }
    }
}
