//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_InvoiceDetails
    {
        public long Invoice_Id { get; set; }
        public string Invoice_Company { get; set; }
        public string Contact_Person { get; set; }
        public string Mobile { get; set; }
        public string LandLine { get; set; }
        public string Fax { get; set; }
        public string Email_ID { get; set; }
        public string CompanyTax_Id { get; set; }
        public string Payment_Terms { get; set; }
        public string Remarks { get; set; }
        public string UpdateUser_id { get; set; }
        public string UpdateUser_name { get; set; }
        public Nullable<System.TimeSpan> sys_time { get; set; }
        public Nullable<System.DateTime> sys_date { get; set; }
        public Nullable<bool> del_status { get; set; }
        public Nullable<long> POrder_Id { get; set; }
    }
}
