//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BankMaster
    {
        public long Bank_id { get; set; }
        public string Bank_Code { get; set; }
        public string Bank_Name { get; set; }
        public string Aba_RoutingNo { get; set; }
        public string ibswiftrouting { get; set; }
        public string Acronymname { get; set; }
        public string IB_BankCode { get; set; }
        public string AgentWps_Id { get; set; }
        public string Ifsc_Code { get; set; }
        public string Branch_name { get; set; }
        public Nullable<long> city_id { get; set; }
        public Nullable<long> state_id { get; set; }
        public Nullable<long> country_id { get; set; }
        public string address { get; set; }
        public string fax { get; set; }
        public string phone_no { get; set; }
        public string website { get; set; }
        public string manager_name { get; set; }
        public string managermobile_no { get; set; }
        public string managerphone_no { get; set; }
        public string manager_Fax { get; set; }
        public string manager_Email { get; set; }
        public Nullable<System.TimeSpan> sys_time { get; set; }
        public Nullable<System.DateTime> sys_date { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<bool> del_status { get; set; }
        public Nullable<long> parentbank_id { get; set; }
        public string parentbank_code { get; set; }
    }
}
