//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customers
    {
        public long cust_id { get; set; }
        public string Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public bool Both_Supplier_Customer { get; set; }
        public string Country { get; set; }
        public string Add_State { get; set; }
        public string City { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string Post_Box { get; set; }
        public string Zip_Code { get; set; }
        public string Land_Line { get; set; }
        public string Fax { get; set; }
        public string Email_Address { get; set; }
        public string Website { get; set; }
        public string OCP_FirstName { get; set; }
        public string OCP_MiddleName { get; set; }
        public string OCP_LastName { get; set; }
        public string OCP_Email { get; set; }
        public string OCP_Designation { get; set; }
        public string OCP_Phone { get; set; }
        public string OCP_Fax { get; set; }
        public string OCP_MobileNo { get; set; }
        public string OCP_Preferred_Contact_Person { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<System.DateTime> Sys_Time { get; set; }
        public Nullable<System.DateTime> Sys_Date { get; set; }
        public string Cus_Status { get; set; }
        public string LedgerAccount { get; set; }
        public Nullable<long> city_id { get; set; }
        public Nullable<long> country_id { get; set; }
        public Nullable<long> state_id { get; set; }
        public Nullable<bool> del_status { get; set; }
        public Nullable<bool> ledgeraccount_status { get; set; }
    }
}
