//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Item_Category
    {
        public long itemcat_id { get; set; }
        public string ItemCategoryID { get; set; }
        public string ItemCategoryDescription { get; set; }
        public Nullable<bool> del_status { get; set; }
    }
}
