//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.Account_Transactions = new HashSet<Account_Transactions>();
        }
    
        public string VoucherNo { get; set; }
        public string VoucherUserNo { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string Currency { get; set; }
        public string ReceivedAmt { get; set; }
        public string ReceivedFrom { get; set; }
        public string TransactionType { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public string RejectedBy { get; set; }
        public string BankName { get; set; }
        public string Branch { get; set; }
        public string ChequeNo { get; set; }
        public string DateOfCheque { get; set; }
        public string ChequeAmount { get; set; }
        public Nullable<System.DateTime> DateCreatedBy { get; set; }
        public Nullable<System.DateTime> DateEditedBy { get; set; }
        public Nullable<System.DateTime> DateApprovedBy { get; set; }
        public Nullable<System.DateTime> DateRejectedBy { get; set; }
        public Nullable<long> EmployerID { get; set; }
        public string BranchId { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account_Transactions> Account_Transactions { get; set; }
        public virtual Allocation Allocation { get; set; }
    }
}
