//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esmart.Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public string WarehouseID { get; set; }
        public string WarehouseName { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string PostBox { get; set; }
        public string ZipCode { get; set; }
        public string LandLine { get; set; }
        public string Fax { get; set; }
        public string EmailAddress { get; set; }
        public string Website { get; set; }
        public string OCP_FirstName { get; set; }
        public string OCP_MiddleName { get; set; }
        public string OCP_LastName { get; set; }
        public string OCP_Email { get; set; }
        public string OCP_Designation { get; set; }
        public string OCP_Phone { get; set; }
        public string OCP_Fax { get; set; }
        public string OCP_MobileNo { get; set; }
        public string OCP_PreferredContactPerson { get; set; }
        public string Create_UserID { get; set; }
        public string Create_UserName { get; set; }
        public string Update_UserID { get; set; }
        public string Update_UserName { get; set; }
        public Nullable<System.DateTime> Sys_Time { get; set; }
        public Nullable<System.DateTime> Sys_Date { get; set; }
    }
}
